#include <iostream.h>

void main()
	{ int Bil1, Bil2;

     cout<<"Masukkan Bilangan pertama :";
     cin>>Bil1;
     cout<<"Masukkan Bilangan Kedua   :";
     cin>>Bil2;
     cout<<"Hasil "<<Bil1<<" + "<<Bil2<<" = "<<(Bil1+Bil2);
     cout<<"Hasil "<<Bil1<<" - "<<Bil2<<" = "<<(Bil1-Bil2);
     cout<<"Hasil "<<Bil1<<" * "<<Bil2<<" = "<<(Bil1*Bil2);
     cout<<"Hasil "<<Bil1<<" / "<<Bil2<<" = "<<(Bil1/Bil2);
     cout<<"Hasil "<<Bil1<<" % "<<Bil2<<" = "<<(Bil1%Bil2);
     return;
}

